// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>gpx11</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>True</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>True</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>True</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace gpx11
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;


    #region Base entity class
    public partial class EntityBase<T>
    {

        private static System.Xml.Serialization.XmlSerializer serializer;

        private static System.Xml.Serialization.XmlSerializer Serializer
        {
            get
            {
                if ((serializer == null))
                {
                    serializer = new System.Xml.Serialization.XmlSerializer(typeof(T));
                }
                return serializer;
            }
        }

        #region Serialize/Deserialize
        /// <summary>
        /// Serializes current EntityBase object into an XML document
        /// </summary>
        /// <returns>string XML value</returns>
        public virtual string Serialize()
        {
            System.IO.StreamReader streamReader = null;
            System.IO.MemoryStream memoryStream = null;
            try
            {
                memoryStream = new System.IO.MemoryStream();
                Serializer.Serialize(memoryStream, this);
                memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
                streamReader = new System.IO.StreamReader(memoryStream);
                return streamReader.ReadToEnd();
            }
            finally
            {
                if ((streamReader != null))
                {
                    streamReader.Dispose();
                }
                if ((memoryStream != null))
                {
                    memoryStream.Dispose();
                }
            }
        }

        /// <summary>
        /// Deserializes workflow markup into an EntityBase object
        /// </summary>
        /// <param name="xml">string workflow markup to deserialize</param>
        /// <param name="obj">Output EntityBase object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool Deserialize(string xml, out T obj, out System.Exception exception)
        {
            exception = null;
            obj = default(T);
            try
            {
                obj = Deserialize(xml);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool Deserialize(string xml, out T obj)
        {
            System.Exception exception = null;
            return Deserialize(xml, out obj, out exception);
        }

        public static T Deserialize(string xml)
        {
            System.IO.StringReader stringReader = null;
            try
            {
                stringReader = new System.IO.StringReader(xml);
                return ((T)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
            }
            finally
            {
                if ((stringReader != null))
                {
                    stringReader.Dispose();
                }
            }
        }

        /// <summary>
        /// Serializes current EntityBase object into file
        /// </summary>
        /// <param name="fileName">full path of outupt xml file</param>
        /// <param name="exception">output Exception value if failed</param>
        /// <returns>true if can serialize and save into file; otherwise, false</returns>
        public virtual bool SaveToFile(string fileName, out System.Exception exception)
        {
            exception = null;
            try
            {
                SaveToFile(fileName);
                return true;
            }
            catch (System.Exception e)
            {
                exception = e;
                return false;
            }
        }

        public virtual void SaveToFile(string fileName)
        {
            System.IO.StreamWriter streamWriter = null;
            try
            {
                string xmlString = Serialize();
                System.IO.FileInfo xmlFile = new System.IO.FileInfo(fileName);
                streamWriter = xmlFile.CreateText();
                streamWriter.WriteLine(xmlString);
                streamWriter.Close();
            }
            finally
            {
                if ((streamWriter != null))
                {
                    streamWriter.Dispose();
                }
            }
        }

        /// <summary>
        /// Deserializes xml markup from file into an EntityBase object
        /// </summary>
        /// <param name="fileName">string xml file to load and deserialize</param>
        /// <param name="obj">Output EntityBase object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool LoadFromFile(string fileName, out T obj, out System.Exception exception)
        {
            exception = null;
            obj = default(T);
            try
            {
                obj = LoadFromFile(fileName);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool LoadFromFile(string fileName, out T obj)
        {
            System.Exception exception = null;
            return LoadFromFile(fileName, out obj, out exception);
        }

        public static T LoadFromFile(string fileName)
        {
            System.IO.FileStream file = null;
            System.IO.StreamReader sr = null;
            try
            {
                file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
                sr = new System.IO.StreamReader(file);
                string xmlString = sr.ReadToEnd();
                sr.Close();
                file.Close();
                return Deserialize(xmlString);
            }
            finally
            {
                if ((file != null))
                {
                    file.Dispose();
                }
                if ((sr != null))
                {
                    sr.Dispose();
                }
            }
        }
        #endregion
    }
    #endregion

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute("gpx", Namespace = "http://www.topografix.com/GPX/1/1", IsNullable = false)]
    public partial class gpxType : EntityBase<gpxType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private metadataType metadataField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<wptType> wptField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<rteType> rteField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<trkType> trkField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private extensionsType extensionsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string versionField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string creatorField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string creator { get; set; }


        public gpxType()
        {
            this.extensionsField = new extensionsType();
            this.trkField = new List<trkType>();
            this.rteField = new List<rteType>();
            this.wptField = new List<wptType>();
            this.metadataField = new metadataType();
            this.versionField = "1.1";
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public metadataType metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("wpt", Order = 1)]
        public List<wptType> wpt
        {
            get
            {
                return this.wptField;
            }
            set
            {
                this.wptField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("rte", Order = 2)]
        public List<rteType> rte
        {
            get
            {
                return this.rteField;
            }
            set
            {
                this.rteField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("trk", Order = 3)]
        public List<trkType> trk
        {
            get
            {
                return this.trkField;
            }
            set
            {
                this.trkField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public extensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.topografix.com/GPX/1/1", IsNullable = true)]
    public partial class metadataType : EntityBase<metadataType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string nameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string descField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private personType authorField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private copyrightType copyrightField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<linkType> linkField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private System.DateTime timeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool timeFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string keywordsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private boundsType boundsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private extensionsType extensionsField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string name { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string desc { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public System.DateTime time { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string keywords { get; set; }


        /// <summary>
        /// metadataType class constructor
        /// </summary>
        public metadataType()
        {
            this.extensionsField = new extensionsType();
            this.boundsField = new boundsType();
            this.linkField = new List<linkType>();
            this.copyrightField = new copyrightType();
            this.authorField = new personType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public personType author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public copyrightType copyright
        {
            get
            {
                return this.copyrightField;
            }
            set
            {
                this.copyrightField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("link", Order = 4)]
        public List<linkType> link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public boundsType bounds
        {
            get
            {
                return this.boundsField;
            }
            set
            {
                this.boundsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public extensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.topografix.com/GPX/1/1", IsNullable = true)]
    public partial class personType : EntityBase<personType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string nameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private emailType emailField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private linkType linkField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string name { get; set; }


        /// <summary>
        /// personType class constructor
        /// </summary>
        public personType()
        {
            this.linkField = new linkType();
            this.emailField = new emailType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public emailType email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public linkType link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.topografix.com/GPX/1/1", IsNullable = true)]
    public partial class emailType : EntityBase<emailType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string idField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string domainField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string domain { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.topografix.com/GPX/1/1", IsNullable = true)]
    public partial class trksegType : EntityBase<trksegType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<wptType> trkptField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private extensionsType extensionsField;

        /// <summary>
        /// trksegType class constructor
        /// </summary>
        public trksegType()
        {
            this.extensionsField = new extensionsType();
            this.trkptField = new List<wptType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("trkpt", Order = 0)]
        public List<wptType> trkpt
        {
            get
            {
                return this.trkptField;
            }
            set
            {
                this.trkptField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public extensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.topografix.com/GPX/1/1", IsNullable = true)]
    public partial class wptType : EntityBase<wptType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal eleField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool eleFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private System.DateTime timeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool timeFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal magvarField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool magvarFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal geoidheightField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool geoidheightFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string nameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string cmtField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string descField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string srcField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<linkType> linkField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string symField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string typeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool fixFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string satField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal hdopField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool hdopFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal vdopField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool vdopFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal pdopField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool pdopFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal ageofdgpsdataField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool ageofdgpsdataFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string dgpsidField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private extensionsType extensionsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal latField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal lonField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public decimal ele { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eleSpecified { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.DateTime time { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public decimal magvar { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool magvarSpecified { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public decimal geoidheight { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool geoidheightSpecified { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string name { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string cmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string desc { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string src { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string sym { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string type { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fixSpecified { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger", Order = 12)]
        public string sat { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public decimal hdop { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hdopSpecified { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public decimal vdop { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdopSpecified { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public decimal pdop { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pdopSpecified { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public decimal ageofdgpsdata { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ageofdgpsdataSpecified { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 17)]
        public string dgpsid { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lat { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lon { get; set; }


        /// <summary>
        /// wptType class constructor
        /// </summary>
        public wptType()
        {
            this.extensionsField = new extensionsType();
            this.linkField = new List<linkType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("link", Order = 8)]
        public List<linkType> link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public fixType fix
        {
            get
            {
                //return this.fixField;
                return this.fix;
            }
            set
            {
                //this.fixField = value;
                this.fix = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public extensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.topografix.com/GPX/1/1", IsNullable = true)]
    public partial class linkType : EntityBase<linkType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string textField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string typeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string hrefField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string text { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string type { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string href { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/1")]
    public enum fixType
    {

        /// <remarks/>
        none,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2d")]
        Item2d,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3d")]
        Item3d,

        /// <remarks/>
        dgps,

        /// <remarks/>
        pps,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.topografix.com/GPX/1/1", IsNullable = true)]
    public partial class extensionsType : EntityBase<extensionsType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<System.Xml.XmlElement> anyField;

        /// <summary>
        /// extensionsType class constructor
        /// </summary>
        public extensionsType()
        {
            this.anyField = new List<System.Xml.XmlElement>();
        }

        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public List<System.Xml.XmlElement> Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.topografix.com/GPX/1/1", IsNullable = true)]
    public partial class trkType : EntityBase<trkType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string nameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string cmtField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string descField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string srcField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<linkType> linkField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string numberField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string typeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private extensionsType extensionsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<trksegType> trksegField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string name { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string cmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string desc { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string src { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger", Order = 5)]
        public string number { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string type { get; set; }


        /// <summary>
        /// trkType class constructor
        /// </summary>
        public trkType()
        {
            this.trksegField = new List<trksegType>();
            this.extensionsField = new extensionsType();
            this.linkField = new List<linkType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("link", Order = 4)]
        public List<linkType> link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public extensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("trkseg", Order = 8)]
        public List<trksegType> trkseg
        {
            get
            {
                return this.trksegField;
            }
            set
            {
                this.trksegField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.topografix.com/GPX/1/1", IsNullable = true)]
    public partial class rteType : EntityBase<rteType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string nameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string cmtField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string descField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string srcField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<linkType> linkField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string numberField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string typeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private extensionsType extensionsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<wptType> rteptField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string name { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string cmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string desc { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string src { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger", Order = 5)]
        public string number { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string type { get; set; }


        /// <summary>
        /// rteType class constructor
        /// </summary>
        public rteType()
        {
            this.rteptField = new List<wptType>();
            this.extensionsField = new extensionsType();
            this.linkField = new List<linkType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("link", Order = 4)]
        public List<linkType> link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public extensionsType extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("rtept", Order = 8)]
        public List<wptType> rtept
        {
            get
            {
                return this.rteptField;
            }
            set
            {
                this.rteptField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.topografix.com/GPX/1/1", IsNullable = true)]
    public partial class boundsType : EntityBase<boundsType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal minlatField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal minlonField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal maxlatField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal maxlonField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal minlat { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal minlon { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxlat { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxlon { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.topografix.com/GPX/1/1", IsNullable = true)]
    public partial class copyrightType : EntityBase<copyrightType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string yearField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string licenseField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string authorField;

        [System.Xml.Serialization.XmlElementAttribute(DataType = "gYear", Order = 0)]
        public string year { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 1)]
        public string license { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string author { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.topografix.com/GPX/1/1", IsNullable = true)]
    public partial class ptType : EntityBase<ptType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal eleField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool eleFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private System.DateTime timeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool timeFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal latField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal lonField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public decimal ele { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eleSpecified { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.DateTime time { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lat { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lon { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.topografix.com/GPX/1/1", IsNullable = true)]
    public partial class ptsegType : EntityBase<ptsegType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<ptType> ptField;

        /// <summary>
        /// ptsegType class constructor
        /// </summary>
        public ptsegType()
        {
            this.ptField = new List<ptType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("pt", Order = 0)]
        public List<ptType> pt
        {
            get
            {
                return this.ptField;
            }
            set
            {
                this.ptField = value;
            }
        }
    }
}
